default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DATABASE_HOST", "db") %>
  port: <%= ENV.fetch("DATABASE_PORT", 5432) %>
  username: <%= ENV.fetch("DATABASE_USERNAME", "departure_desk") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "departure_desk_dev") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  variables:
    statement_timeout: <%= ENV.fetch("DB_STATEMENT_TIMEOUT", "15s") %>
    lock_timeout: <%= ENV.fetch("DB_LOCK_TIMEOUT", "5s") %>

development:
  primary:
    <<: *default
    database: <%= ENV.fetch("DATABASE_NAME", "departure_desk_development") %>

  queue:
    <<: *default
    database: <%= ENV.fetch(
      "QUEUE_DATABASE_NAME",
      "departure_desk_development_queue"
    ) %>
    migrations_paths: db/queue_migrate

test:
  primary:
    <<: *default
    database: <%= ENV.fetch("TEST_DATABASE_NAME", "departure_desk_test") %>

  queue:
    <<: *default
    database: <%= ENV.fetch(
      "TEST_QUEUE_DATABASE_NAME",
      "departure_desk_test_queue"
    ) %>
    migrations_paths: db/queue_migrate

production:
  primary:
    url: <%= ENV["DATABASE_URL"] %>

  queue:
    url: <%= ENV["QUEUE_DATABASE_URL"] %>
    migrations_paths: db/queue_migrate